jobs:

  - name: manifest1
    type: manifest
    steps:
      - IN: image1
    flags: 
      manifest
  - name: runsh
    type: runSh
    steps:
      - IN: sample-script
      - IN: tg1
      - IN: manifest1
      - IN: image2
      - TASK:
        - script: ./IN/sample-script/gitRepo/echo.sh
        #- echo 'testrunShscriptout'
        #- ls
    on_success:
      - NOTIFY: myEmailS1
      - NOTIFY: mySlackS1
      - script: echo 'test'
      - script: echo 'newtesting success'
      
