jobs:
  - name: runsh
    type: runSh
    steps:
      - IN: sample-script
      - IN: tg1
      - TASK:
        - script: ./IN/sample-script/gitRepo/echo.sh
        - echo 'testrunShscriptout'
        - ls
    on_success:
      - NOTIFY: myEmailS1
      - NOTIFY: mySlackS1
      
